### ISSUE TITLE
Does this work with UDP

### ISSUE THREAD

**Issue by weepy** [johanholmerin/worker-webrtc#4]
Hi - I was trying to understand what transport this uses to send data.

I want to send binary data over WebRTC for a worker with maxRetries = 0

Do you know if this is possible with this library ?

**Comment by johanholmerin** [comment]
This library just forwards all calls to browsers main-thread WebRTC implementation. Furthermore, WebRTC uses SCTP. What you can do is specify `ordered`, `maxRetransmits`, etc. when calling [createDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createDataChannel)

**Comment by weepy** [comment]
Gotcha thanks. So there’s not much point for my use case where I want to
avoid blocking the main thread to send webrtc data ?
